secret.TMDB.API.Key = eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5YjA2NDg5YmE2ZjA2M2M5YTMzY2JlYTBmMzJiNzAzOSIsIm5iZiI6MTc2NDUwOTQ5Mi4zMzcsInN1YiI6IjY5MmM0NzM0OWQzMmI4YTk0MjNiODg0YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.XzJrUpMvSO-LzDwLcpA1XBX2k0zfsJLMSjtifvtPPBc
media.refresh.cron = 0 0 3 * * *
server.port = 8081
spring.datasource.url=jdbc:postgresql://localhost:5432/Licenta
spring.datasource.username=postgres
spring.datasource.password=123437

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true